name: country_state_city_pro
description: A new Flutter package to get world's all of Country, State, and City.
version: 0.0.6
homepage: https://github.com/SujitSarkar/Country-State-City-Picker-Pro

environment:
#  sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - packages/country_state_city_pro/assets/country.json
    - packages/country_state_city_pro/assets/state.json
    - packages/country_state_city_pro/assets/city.json
